In [1]:
import pandas as pd
import numpy as np

In [2]:
campaign = pd.read_excel('CampaignSubjects.xlsx')
choice = pd.read_excel('ChoiceSubjectsData.xlsx')

In [3]:
campaign

,Id,SubjectType,SubjectName,SubjectValues
0,"""f36cb6ff-8df4-4842-b59f-d05153bbb560""",SingleSelect,Did you buy Chickapea pasta after trying the s...,"[""No"",""Yes""]"
1,"""d7f7cebb-baa8-41ce-95c5-688f86e50a75""",SingleSelect,Have you ever tried legume-based pasta before?...,"[""No"",""Yes""]"
2,"""80011846-c284-4aa7-9742-8c3f16e131b7""",SingleSelect,How many boxes of Chickapea pasta did you buy?,"[""1"",""2-3"",""4-5"",""More than 5""]"
3,"""3c327491-9c15-4ab3-bdb9-8d2aafbbf87e""",SingleSelect,User Distribution,"[""Activation (Dormant)"",""Acquisition (New-to-b..."
4,"""e0b39b39-682d-462d-ab23-8de2577628fe""",LocationData,Province,"[""Alabama"",""US"",""Alaska"",""US"",""Alberta"",""CA"",""..."
5,"""9afaec0d-f7a8-4cc7-90a2-b77d5d62c922""",SingleSelect,Gender,"[""Female"",""I would rather not say"",""Male"",""Non..."
6,"""ecb57a0f-3779-4ded-99a7-1fa4d9c6a14f""",SingleSelect,Do you have any kids?,"[""Expecting Children"",""No"",""Yes""]"
7,"""90c36fb3-1cf8-4659-b2bd-6d1dce401ba0""",LocationData,Country,"[""CA"",""US""]"
8,"""8e630a29-7f74-41f8-9023-813459d7e254""",SingleSelect,How old are your kids?,"[""0 to 1 years old"",""1 to 3 years old"",""3 to 5..."
9,"""90f8fee2-9939-4dc3-a91c-2da82a2f8053""",SingleSelect,Age Range,"[""20-30"",""31-40"",""41-50"",""51-60"",""61-70"",""Unde..."
10,"""e4eeb58a-5c80-428d-bf24-7372867dd28d""",MutliSelect,Which of the following stores can you easily a...,"[""Albertsons"",""H-E-B"",""Kroger"",""Meijer"",""Other..."
11,"""935791bc-4831-4386-aa99-90f3c3ddb571""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
12,"""044a1964-ec46-4404-9089-120f41dd0f54""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
13,"""e8e6cdbe-9500-4eef-a117-1a31c5c35990""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
14,"""8ca14928-2fbe-42b6-8713-5b4e17459f80""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
15,"""a3dff33b-48f5-42fd-962e-942d8b0a6678""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
16,"""206cb04a-9519-4623-8109-8b6cf43f224e""",SingleSelect,How do you rate the taste of the pasta?,"[""1"",""2"",""3"",""4"",""5""]"
17,"""db098389-9e70-4b6b-ab75-8155ac596158""",SingleSelect,How do you rate the texture of the pasta?,"[""1"",""2"",""3"",""4"",""5""]"
18,"""145591d2-2d08-42da-b48e-60c615c93ef0""",SingleSelect,How does the taste and texture of Chickapea pa...,"[""About the same"",""Better"",""This was my first ..."
19,"""ba7ff179-0a65-4ad2-849f-06b02425355c""",SingleSelect,How often are you planning to purchase Chickap...,"[""I’m not going to buy it"",""Once a month"",""Onc..."
20,"""2cb637a8-25d5-4711-b237-d0f30a4fc69e""",SingleSelect,How often do you eat pasta?,"[""A couple of times a month"",""More than 2 time..."
21,"""10e312b7-1324-4335-8e82-ba0db197f99f""",MutliSelect,If not planning to buy it at least once a mont...,"[""Didn’t like the taste or texture"",""I eat pas..."
22,"""e0c8ecf3-ea97-455a-932a-0b4706f8a620""",SingleSelect,"On a scale of 0 to 10, how likely are you to r...","[""0"",""1"",""10"",""2"",""3"",""4"",""5"",""6"",""7"",""8"",""9""]"
23,"""6cd4d59a-c733-423f-8348-d59f652eb6e5""",SingleSelect,Purchase Intent,"[""No"",""Yes""]"
24,"""9c71a15c-79ff-4981-adbf-41a116e59126""",MutliSelect,What could be improved about Chickapea Spirals?,"[""Flavor (Taste)"",""Ingredients"",""Nothing (it w..."
25,"""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",MutliSelect,What did you like the most about Chickapea Spi...,"[""Flavor (Taste)"",""Ingredients"",""Nothing"",""Nut..."
26,"""1450e285-a0bf-4306-bcb0-964b38720b9c""",MutliSelect,Where did you buy Chickapea pasta?,"[""Amazon"",""Brands's website"",""Fresh Thyme"",""Ha..."
27,"""8723124d-771b-4717-8e32-d49189a81473""",MutliSelect,Which brand(s) comes to mind when you think ab...,"[""Banza"",""Barilla Protein+"",""Brami"",""Chickapea..."
28,"""0dfd73bd-6c6e-400c-a036-0ec64085cbeb""",OpenText,Please provide a brief review of the pasta you...,NaN

In [4]:
choice

,RecordId,SamplerId,CampaignSubjectId,SubjectValue
0,"""ac53fafb-7db0-4a5b-a8d6-2c18fab493fb""","""0f98a10f-f296-4808-a7ec-2d20c60bb1cf""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Kroger
1,"""57e7cbef-0cc4-45cf-9cb3-644ec73b59db""","""ae3f98ed-cee7-4645-80f2-bb4c620e9897""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Other
2,"""24e414a4-9972-4314-b513-26a52df4eb3d""","""92e80710-705b-48b3-ac62-962005cc254b""","""206cb04a-9519-4623-8109-8b6cf43f224e""",4
3,"""fa99ef64-dcb9-4893-9df4-ce1dadb259da""","""d03f6cf3-5a10-4d9f-8922-6033f3a39688""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Ingredients
4,"""a8daeaa2-d746-4cfb-a3df-570451a2a833""","""4d8be7ea-65a4-427f-8e77-368883fe5193""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Texture
...,...,...,...,...
24250,"""d8712e44-6d34-4542-bf7d-ae85ae9936ae""","""b310ed8c-9610-4079-8b43-d70d678ac7ba""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes
24251,"""7ecb178d-6043-41dd-b758-e2978098a388""","""3c5f356a-fc6f-4873-aadf-6099eb3d10cb""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes
24252,"""39b4d277-dc1f-4684-babb-7dc4ac823e13""","""ff11c90d-3152-4d2c-85cc-0da30b6b119c""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes
24253,"""0faeb424-c84e-4ece-9645-97960c6e861c""","""bae1a189-3e4a-489c-b462-c4b20400d0e4""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes
24254,"""662a0e45-6d00-4f4f-a880-ae459c2c693f""","""ddb13109-9906-411b-b345-2602d4a255fa""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes

 # Now we want to extract the data from choice by using the campaign datas

### CampaignSubjectId datas in choice df is similiar with Id in campaign df

In [5]:
campaign = campaign.rename(columns={'Id': 'CampaignSubjectId'})
campaign

,CampaignSubjectId,SubjectType,SubjectName,SubjectValues
0,"""f36cb6ff-8df4-4842-b59f-d05153bbb560""",SingleSelect,Did you buy Chickapea pasta after trying the s...,"[""No"",""Yes""]"
1,"""d7f7cebb-baa8-41ce-95c5-688f86e50a75""",SingleSelect,Have you ever tried legume-based pasta before?...,"[""No"",""Yes""]"
2,"""80011846-c284-4aa7-9742-8c3f16e131b7""",SingleSelect,How many boxes of Chickapea pasta did you buy?,"[""1"",""2-3"",""4-5"",""More than 5""]"
3,"""3c327491-9c15-4ab3-bdb9-8d2aafbbf87e""",SingleSelect,User Distribution,"[""Activation (Dormant)"",""Acquisition (New-to-b..."
4,"""e0b39b39-682d-462d-ab23-8de2577628fe""",LocationData,Province,"[""Alabama"",""US"",""Alaska"",""US"",""Alberta"",""CA"",""..."
5,"""9afaec0d-f7a8-4cc7-90a2-b77d5d62c922""",SingleSelect,Gender,"[""Female"",""I would rather not say"",""Male"",""Non..."
6,"""ecb57a0f-3779-4ded-99a7-1fa4d9c6a14f""",SingleSelect,Do you have any kids?,"[""Expecting Children"",""No"",""Yes""]"
7,"""90c36fb3-1cf8-4659-b2bd-6d1dce401ba0""",LocationData,Country,"[""CA"",""US""]"
8,"""8e630a29-7f74-41f8-9023-813459d7e254""",SingleSelect,How old are your kids?,"[""0 to 1 years old"",""1 to 3 years old"",""3 to 5..."
9,"""90f8fee2-9939-4dc3-a91c-2da82a2f8053""",SingleSelect,Age Range,"[""20-30"",""31-40"",""41-50"",""51-60"",""61-70"",""Unde..."
10,"""e4eeb58a-5c80-428d-bf24-7372867dd28d""",MutliSelect,Which of the following stores can you easily a...,"[""Albertsons"",""H-E-B"",""Kroger"",""Meijer"",""Other..."
11,"""935791bc-4831-4386-aa99-90f3c3ddb571""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
12,"""044a1964-ec46-4404-9089-120f41dd0f54""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
13,"""e8e6cdbe-9500-4eef-a117-1a31c5c35990""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
14,"""8ca14928-2fbe-42b6-8713-5b4e17459f80""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
15,"""a3dff33b-48f5-42fd-962e-942d8b0a6678""",SingleSelect,How do you rate each of these characteristics ...,"[""😊"",""😍"",""😐"",""😒""]"
16,"""206cb04a-9519-4623-8109-8b6cf43f224e""",SingleSelect,How do you rate the taste of the pasta?,"[""1"",""2"",""3"",""4"",""5""]"
17,"""db098389-9e70-4b6b-ab75-8155ac596158""",SingleSelect,How do you rate the texture of the pasta?,"[""1"",""2"",""3"",""4"",""5""]"
18,"""145591d2-2d08-42da-b48e-60c615c93ef0""",SingleSelect,How does the taste and texture of Chickapea pa...,"[""About the same"",""Better"",""This was my first ..."
19,"""ba7ff179-0a65-4ad2-849f-06b02425355c""",SingleSelect,How often are you planning to purchase Chickap...,"[""I’m not going to buy it"",""Once a month"",""Onc..."
20,"""2cb637a8-25d5-4711-b237-d0f30a4fc69e""",SingleSelect,How often do you eat pasta?,"[""A couple of times a month"",""More than 2 time..."
21,"""10e312b7-1324-4335-8e82-ba0db197f99f""",MutliSelect,If not planning to buy it at least once a mont...,"[""Didn’t like the taste or texture"",""I eat pas..."
22,"""e0c8ecf3-ea97-455a-932a-0b4706f8a620""",SingleSelect,"On a scale of 0 to 10, how likely are you to r...","[""0"",""1"",""10"",""2"",""3"",""4"",""5"",""6"",""7"",""8"",""9""]"
23,"""6cd4d59a-c733-423f-8348-d59f652eb6e5""",SingleSelect,Purchase Intent,"[""No"",""Yes""]"
24,"""9c71a15c-79ff-4981-adbf-41a116e59126""",MutliSelect,What could be improved about Chickapea Spirals?,"[""Flavor (Taste)"",""Ingredients"",""Nothing (it w..."
25,"""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",MutliSelect,What did you like the most about Chickapea Spi...,"[""Flavor (Taste)"",""Ingredients"",""Nothing"",""Nut..."
26,"""1450e285-a0bf-4306-bcb0-964b38720b9c""",MutliSelect,Where did you buy Chickapea pasta?,"[""Amazon"",""Brands's website"",""Fresh Thyme"",""Ha..."
27,"""8723124d-771b-4717-8e32-d49189a81473""",MutliSelect,Which brand(s) comes to mind when you think ab...,"[""Banza"",""Barilla Protein+"",""Brami"",""Chickapea..."
28,"""0dfd73bd-6c6e-400c-a036-0ec64085cbeb""",OpenText,Please provide a brief review of the pasta you...,NaN

### It is Id of questions (Features) in choice df and its SubjectValue are the related answers.


### Now we want to replace the features in 'CampaignSubjectId' in choice df

In [6]:
choice = choice.merge(
    campaign[['CampaignSubjectId', 'SubjectName']],
    on= 'CampaignSubjectId',
    how= 'left'
)
choice

,RecordId,SamplerId,CampaignSubjectId,SubjectValue,SubjectName
0,"""ac53fafb-7db0-4a5b-a8d6-2c18fab493fb""","""0f98a10f-f296-4808-a7ec-2d20c60bb1cf""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Kroger,Where did you buy Chickapea pasta?
1,"""57e7cbef-0cc4-45cf-9cb3-644ec73b59db""","""ae3f98ed-cee7-4645-80f2-bb4c620e9897""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Other,Where did you buy Chickapea pasta?
2,"""24e414a4-9972-4314-b513-26a52df4eb3d""","""92e80710-705b-48b3-ac62-962005cc254b""","""206cb04a-9519-4623-8109-8b6cf43f224e""",4,How do you rate the taste of the pasta?
3,"""fa99ef64-dcb9-4893-9df4-ce1dadb259da""","""d03f6cf3-5a10-4d9f-8922-6033f3a39688""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Ingredients,What did you like the most about Chickapea Spi...
4,"""a8daeaa2-d746-4cfb-a3df-570451a2a833""","""4d8be7ea-65a4-427f-8e77-368883fe5193""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Texture,What did you like the most about Chickapea Spi...
...,...,...,...,...,...
24250,"""d8712e44-6d34-4542-bf7d-ae85ae9936ae""","""b310ed8c-9610-4079-8b43-d70d678ac7ba""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes,NaN
24251,"""7ecb178d-6043-41dd-b758-e2978098a388""","""3c5f356a-fc6f-4873-aadf-6099eb3d10cb""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes,NaN
24252,"""39b4d277-dc1f-4684-babb-7dc4ac823e13""","""ff11c90d-3152-4d2c-85cc-0da30b6b119c""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes,NaN
24253,"""0faeb424-c84e-4ece-9645-97960c6e861c""","""bae1a189-3e4a-489c-b462-c4b20400d0e4""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes,NaN
24254,"""662a0e45-6d00-4f4f-a880-ae459c2c693f""","""ddb13109-9906-411b-b345-2602d4a255fa""","""347c0747-787f-4d39-8176-e076649d80fa""",Yes,NaN

### In above we have some 'CampaignSubjectId' datas which their 'SubjectName' is Nan. It means the features are not defined. So we need to remove them.

In [7]:
choice = choice[choice['SubjectName'].notna()]
choice

,RecordId,SamplerId,CampaignSubjectId,SubjectValue,SubjectName
0,"""ac53fafb-7db0-4a5b-a8d6-2c18fab493fb""","""0f98a10f-f296-4808-a7ec-2d20c60bb1cf""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Kroger,Where did you buy Chickapea pasta?
1,"""57e7cbef-0cc4-45cf-9cb3-644ec73b59db""","""ae3f98ed-cee7-4645-80f2-bb4c620e9897""","""1450e285-a0bf-4306-bcb0-964b38720b9c""",Other,Where did you buy Chickapea pasta?
2,"""24e414a4-9972-4314-b513-26a52df4eb3d""","""92e80710-705b-48b3-ac62-962005cc254b""","""206cb04a-9519-4623-8109-8b6cf43f224e""",4,How do you rate the taste of the pasta?
3,"""fa99ef64-dcb9-4893-9df4-ce1dadb259da""","""d03f6cf3-5a10-4d9f-8922-6033f3a39688""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Ingredients,What did you like the most about Chickapea Spi...
4,"""a8daeaa2-d746-4cfb-a3df-570451a2a833""","""4d8be7ea-65a4-427f-8e77-368883fe5193""","""7f3e04bb-5e0d-48f6-a9ac-2f210aec9f97""",Texture,What did you like the most about Chickapea Spi...
...,...,...,...,...,...
23230,"""841f48b7-0163-4985-8d28-9ae92311a0ee""","""8037afdb-c0ae-4d4f-b667-8616e80188b7""","""145591d2-2d08-42da-b48e-60c615c93ef0""",This was my first chickpea pasta,How does the taste and texture of Chickapea pa...
23231,"""9f2caa82-5d28-47c5-9acd-99429cbb4be3""","""13c887ba-fef7-4622-a343-7c2259d26736""","""145591d2-2d08-42da-b48e-60c615c93ef0""",This was my first chickpea pasta,How does the taste and texture of Chickapea pa...
23232,"""640cd1e8-630b-40a5-863c-cfcc3dfdbd27""","""8f798105-ee3f-4a53-928b-c1e04d6de132""","""145591d2-2d08-42da-b48e-60c615c93ef0""",This was my first chickpea pasta,How does the taste and texture of Chickapea pa...
23233,"""1cc6c2c5-a024-4113-a95b-326cca7bc1ca""","""cad687f8-b109-4284-b3a4-f2349413e12a""","""145591d2-2d08-42da-b48e-60c615c93ef0""",This was my first chickpea pasta,How does the taste and texture of Chickapea pa...
23234,"""0bb58e36-663b-4cbc-9861-ab1053eacc11""","""2ac24228-101d-4ec5-90e2-1b95c56f019c""","""145591d2-2d08-42da-b48e-60c615c93ef0""",This was my first chickpea pasta,How does the taste and texture of Chickapea pa...

### Now I want to separate the SamplerId and put SubjectName as feature with related SubjectValue.

In [8]:
main_df = (
    choice
    .pivot_table(
        index="SamplerId",
        columns="SubjectName",
        values="SubjectValue",
        aggfunc="first"
    )
    .reset_index()
)
main_df

SubjectName,SamplerId,Age Range,Country,Did you buy Chickapea pasta after trying the sample?,Do you have any kids?,Gender,"Have you ever tried legume-based pasta before? (chickpea, lentil, pea, bean, etc.)",How do you rate each of these characteristics of Chickapea packaging?: Clarity of information,"How do you rate each of these characteristics of Chickapea packaging?: Ease of use (Open, reseal, and handle)",How do you rate each of these characteristics of Chickapea packaging?: Overall packaging,...,"If not planning to buy it at least once a month, why not?","On a scale of 0 to 10, how likely are you to recommend Chickapea pasta to a friend or colleague?",Province,Purchase Intent,User Distribution,What could be improved about Chickapea Spirals?,What did you like the most about Chickapea Spirals?,Where did you buy Chickapea pasta?,Which brand(s) comes to mind when you think about high protein pasta?,Which of the following stores can you easily access?
0,"""00252e52-9e6f-4dc2-821e-0a2d0d0b5940""",41-50,US,No,No,Female,Yes,😍,😍,😊,...,NaN,9,"California, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Ingredients,NaN,Veggiecraft Farms,Whole Foods Market
1,"""0067fb06-29d8-4bc4-93b2-4cf1e505d122""",51-60,US,No,Yes,Female,Yes,😍,😍,😍,...,NaN,10,"Illinois, US",Yes,Activation (Dormant),Price ($3.99/box),Flavor (Taste),NaN,Brami,Whole Foods Market
2,"""009c1337-4a4e-44b0-a130-a824cdc0dc6d""",41-50,US,No,Yes,Female,No,😍,😍,😍,...,NaN,7,"California, US",Yes,Acquisition (New-to-brand),Flavor (Taste),Price ($3.99/box),NaN,Chickapea,Albertsons
3,"""012cae1c-db14-469a-862e-d72e21ffdee1""",41-50,US,No,Yes,Female,Yes,😍,😍,😊,...,NaN,8,"Arizona, US",Yes,Acquisition (New-to-brand),Texture,Flavor (Taste),NaN,Barilla Protein+,Albertsons
4,"""01860c38-9987-48d9-871c-69a1272f49a1""",51-60,US,Yes,Yes,Female,No,😍,😍,😍,...,NaN,10,"California, US",Yes,Acquisition (New-to-brand),NaN,Ingredients,Other,None of the above,Sprouts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,"""fd6eb01a-3f2d-4e6d-85db-c11ec2d99d40""",41-50,US,No,Yes,Male,Yes,😊,😊,😊,...,NaN,6,"Georgia, US",Yes,Acquisition (New-to-brand),Texture,Nutritional benefits,Amazon,Barilla Protein+,Other
727,"""fd94de0d-a80f-486e-9d3e-1aeb6fc289b9""",51-60,US,No,No,Female,Yes,😍,😍,😍,...,NaN,10,"Ohio, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Fresh Thyme,Other,Meijer
728,"""feb1699c-ad00-49f4-881b-9c101fdc06c5""",51-60,US,No,Yes,Female,Yes,😍,😍,😊,...,NaN,9,"California, US",Yes,Activation (Dormant),Price ($3.99/box),Nutritional benefits,NaN,Chickapea,Walmart
729,"""feb2c322-5627-43c7-8810-ccb37c07d76c""",20-30,US,No,Yes,Female,No,😍,😍,😍,...,NaN,10,"South Carolina, US",Yes,Acquisition (New-to-brand),NaN,Texture,NaN,Veggiecraft Farms,Walmart
730,"""ff3db08e-b008-43ad-87b5-64b46fbf75c3""",31-40,US,Yes,Yes,Female,Yes,😊,😊,😒,...,NaN,6,"Florida, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Publix,Chickapea,Publix

### Finally Our main_df is created. Lets save it.

In [9]:
main_df.to_csv('Main DF.csv', index=False)

### As some of the features are long, it should be better to replace the small and suitable words to them

In [10]:
rename_features = {
    "Did you buy Chickapea pasta after trying the sample?": "Bought After sample",
    "Do you have any kids?": "Has Kids",
    "How old are your kids?": "Kids Year",
    "Have you ever tried legume-based pasta before? (chickpea, lentil, pea, bean, etc.)": "Tried Legume Pasta",
    "On a scale of 0 to 10, how likely are you to recommend Chickapea pasta to a friend or colleague?": "Pasta Recommendation Scale",

    "How do you rate each of these characteristics of Chickapea packaging?: Clarity of information": "Clarity Packaging",
    "How do you rate each of these characteristics of Chickapea packaging?: Ease of use (Open, reseal, and handle)": "Ease Packaging",
    "How do you rate each of these characteristics of Chickapea packaging?: Overall packaging": "Overall Packaging",
    "How do you rate each of these characteristics of Chickapea packaging?: Sustainability": "Sustainability Packaging",
    "How do you rate each of these characteristics of Chickapea packaging?: Visual appeal": "Visual Packaging",

    "If not planning to buy it at least once a month, why not?": "Not Monthly Buy",
    "What could be improved about Chickapea Spirals?": "Improve Areas",
    "What did you like the most about Chickapea Spirals?": "Liked Most",
    "How many boxes of Chickapea pasta did you buy?": "Pasta Boxes",

    "Where did you buy Chickapea pasta?": "Pasta Channel",
    "Which brand(s) comes to mind when you think about high protein pasta?": "Brand Recall",
    "Which of the following stores can you easily access?": "Easy Access Store",

    "How do you rate the taste of the pasta?": "Taste Rate",
    "How do you rate the texture of the pasta?": "Texture Rate",
    "How does the taste and texture of Chickapea pasta compare to other chickpea-based pasta you tried?" : "Taste Texture Comparision",
    "How often are you planning to purchase Chickapea pasta in the future?" : "Purchase Planning",
    "How often do you eat pasta?": "Pasta Usage",
    "Please provide a brief review of the pasta you had from Chickapea.": "Review"
}
main_df = main_df.rename(columns=rename_features)
main_df

SubjectName,SamplerId,Age Range,Country,Bought After sample,Has Kids,Gender,Tried Legume Pasta,Clarity Packaging,Ease Packaging,Overall Packaging,...,Not Monthly Buy,Pasta Recommendation Scale,Province,Purchase Intent,User Distribution,Improve Areas,Liked Most,Pasta Channel,Brand Recall,Easy Access Store
0,"""00252e52-9e6f-4dc2-821e-0a2d0d0b5940""",41-50,US,No,No,Female,Yes,😍,😍,😊,...,NaN,9,"California, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Ingredients,NaN,Veggiecraft Farms,Whole Foods Market
1,"""0067fb06-29d8-4bc4-93b2-4cf1e505d122""",51-60,US,No,Yes,Female,Yes,😍,😍,😍,...,NaN,10,"Illinois, US",Yes,Activation (Dormant),Price ($3.99/box),Flavor (Taste),NaN,Brami,Whole Foods Market
2,"""009c1337-4a4e-44b0-a130-a824cdc0dc6d""",41-50,US,No,Yes,Female,No,😍,😍,😍,...,NaN,7,"California, US",Yes,Acquisition (New-to-brand),Flavor (Taste),Price ($3.99/box),NaN,Chickapea,Albertsons
3,"""012cae1c-db14-469a-862e-d72e21ffdee1""",41-50,US,No,Yes,Female,Yes,😍,😍,😊,...,NaN,8,"Arizona, US",Yes,Acquisition (New-to-brand),Texture,Flavor (Taste),NaN,Barilla Protein+,Albertsons
4,"""01860c38-9987-48d9-871c-69a1272f49a1""",51-60,US,Yes,Yes,Female,No,😍,😍,😍,...,NaN,10,"California, US",Yes,Acquisition (New-to-brand),NaN,Ingredients,Other,None of the above,Sprouts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,"""fd6eb01a-3f2d-4e6d-85db-c11ec2d99d40""",41-50,US,No,Yes,Male,Yes,😊,😊,😊,...,NaN,6,"Georgia, US",Yes,Acquisition (New-to-brand),Texture,Nutritional benefits,Amazon,Barilla Protein+,Other
727,"""fd94de0d-a80f-486e-9d3e-1aeb6fc289b9""",51-60,US,No,No,Female,Yes,😍,😍,😍,...,NaN,10,"Ohio, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Fresh Thyme,Other,Meijer
728,"""feb1699c-ad00-49f4-881b-9c101fdc06c5""",51-60,US,No,Yes,Female,Yes,😍,😍,😊,...,NaN,9,"California, US",Yes,Activation (Dormant),Price ($3.99/box),Nutritional benefits,NaN,Chickapea,Walmart
729,"""feb2c322-5627-43c7-8810-ccb37c07d76c""",20-30,US,No,Yes,Female,No,😍,😍,😍,...,NaN,10,"South Carolina, US",Yes,Acquisition (New-to-brand),NaN,Texture,NaN,Veggiecraft Farms,Walmart
730,"""ff3db08e-b008-43ad-87b5-64b46fbf75c3""",31-40,US,Yes,Yes,Female,Yes,😊,😊,😒,...,NaN,6,"Florida, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Publix,Chickapea,Publix

### As I checked, there are some NaNs. We can rearrange or remove the NaNs, if needed.

In [11]:
main_df.isna().sum()

SubjectName
SamplerId                       0
Age Range                       0
Country                         0
Bought After sample             0
Has Kids                        0
Gender                          0
Tried Legume Pasta              0
Clarity Packaging               3
Ease Packaging                  3
Overall Packaging               0
Sustainability Packaging        3
Visual Packaging                0
Taste Rate                      0
Texture Rate                    0
Taste Texture Comparision       0
Pasta Boxes                   406
Purchase Planning               0
Pasta Usage                     0
Kids Year                       0
Not Monthly Buy               664
Pasta Recommendation Scale      0
Province                        0
Purchase Intent                 0
User Distribution               0
Improve Areas                   6
Liked Most                      0
Pasta Channel                 406
Brand Recall                    0
Easy Access Store               0
dtype: int64

### Also we will change the emojis and 'Yes/No' to numerical datas.

In [12]:
emoji_cols = [
    "Clarity Packaging",
    "Ease Packaging",
    "Overall Packaging",
    "Sustainability Packaging",
    "Visual Packaging"
]

emoji_map = {
    "😍": 4,
    "😊": 3,
    "😐": 2,
    "😒": 1
}

for col in emoji_cols:
    main_df[col] = main_df[col].map(emoji_map).astype("Int64")

main_df

SubjectName,SamplerId,Age Range,Country,Bought After sample,Has Kids,Gender,Tried Legume Pasta,Clarity Packaging,Ease Packaging,Overall Packaging,...,Not Monthly Buy,Pasta Recommendation Scale,Province,Purchase Intent,User Distribution,Improve Areas,Liked Most,Pasta Channel,Brand Recall,Easy Access Store
0,"""00252e52-9e6f-4dc2-821e-0a2d0d0b5940""",41-50,US,No,No,Female,Yes,4,4,3,...,NaN,9,"California, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Ingredients,NaN,Veggiecraft Farms,Whole Foods Market
1,"""0067fb06-29d8-4bc4-93b2-4cf1e505d122""",51-60,US,No,Yes,Female,Yes,4,4,4,...,NaN,10,"Illinois, US",Yes,Activation (Dormant),Price ($3.99/box),Flavor (Taste),NaN,Brami,Whole Foods Market
2,"""009c1337-4a4e-44b0-a130-a824cdc0dc6d""",41-50,US,No,Yes,Female,No,4,4,4,...,NaN,7,"California, US",Yes,Acquisition (New-to-brand),Flavor (Taste),Price ($3.99/box),NaN,Chickapea,Albertsons
3,"""012cae1c-db14-469a-862e-d72e21ffdee1""",41-50,US,No,Yes,Female,Yes,4,4,3,...,NaN,8,"Arizona, US",Yes,Acquisition (New-to-brand),Texture,Flavor (Taste),NaN,Barilla Protein+,Albertsons
4,"""01860c38-9987-48d9-871c-69a1272f49a1""",51-60,US,Yes,Yes,Female,No,4,4,4,...,NaN,10,"California, US",Yes,Acquisition (New-to-brand),NaN,Ingredients,Other,None of the above,Sprouts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,"""fd6eb01a-3f2d-4e6d-85db-c11ec2d99d40""",41-50,US,No,Yes,Male,Yes,3,3,3,...,NaN,6,"Georgia, US",Yes,Acquisition (New-to-brand),Texture,Nutritional benefits,Amazon,Barilla Protein+,Other
727,"""fd94de0d-a80f-486e-9d3e-1aeb6fc289b9""",51-60,US,No,No,Female,Yes,4,4,4,...,NaN,10,"Ohio, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Fresh Thyme,Other,Meijer
728,"""feb1699c-ad00-49f4-881b-9c101fdc06c5""",51-60,US,No,Yes,Female,Yes,4,4,3,...,NaN,9,"California, US",Yes,Activation (Dormant),Price ($3.99/box),Nutritional benefits,NaN,Chickapea,Walmart
729,"""feb2c322-5627-43c7-8810-ccb37c07d76c""",20-30,US,No,Yes,Female,No,4,4,4,...,NaN,10,"South Carolina, US",Yes,Acquisition (New-to-brand),NaN,Texture,NaN,Veggiecraft Farms,Walmart
730,"""ff3db08e-b008-43ad-87b5-64b46fbf75c3""",31-40,US,Yes,Yes,Female,Yes,3,3,1,...,NaN,6,"Florida, US",Yes,Acquisition (New-to-brand),Price ($3.99/box),Texture,Publix,Chickapea,Publix

In [13]:
boolean_cols = [
    "Bought After sample",
    "Has Kids",
    "Tried Legume Pasta",
    "Purchase Intent"
]

boolean_map = {"No": 0, "Yes": 1}

for col in boolean_cols:
    main_df[col] = main_df[col].map(boolean_map).astype("Int64")

main_df

SubjectName,SamplerId,Age Range,Country,Bought After sample,Has Kids,Gender,Tried Legume Pasta,Clarity Packaging,Ease Packaging,Overall Packaging,...,Not Monthly Buy,Pasta Recommendation Scale,Province,Purchase Intent,User Distribution,Improve Areas,Liked Most,Pasta Channel,Brand Recall,Easy Access Store
0,"""00252e52-9e6f-4dc2-821e-0a2d0d0b5940""",41-50,US,0,0,Female,1,4,4,3,...,NaN,9,"California, US",1,Acquisition (New-to-brand),Price ($3.99/box),Ingredients,NaN,Veggiecraft Farms,Whole Foods Market
1,"""0067fb06-29d8-4bc4-93b2-4cf1e505d122""",51-60,US,0,1,Female,1,4,4,4,...,NaN,10,"Illinois, US",1,Activation (Dormant),Price ($3.99/box),Flavor (Taste),NaN,Brami,Whole Foods Market
2,"""009c1337-4a4e-44b0-a130-a824cdc0dc6d""",41-50,US,0,1,Female,0,4,4,4,...,NaN,7,"California, US",1,Acquisition (New-to-brand),Flavor (Taste),Price ($3.99/box),NaN,Chickapea,Albertsons
3,"""012cae1c-db14-469a-862e-d72e21ffdee1""",41-50,US,0,1,Female,1,4,4,3,...,NaN,8,"Arizona, US",1,Acquisition (New-to-brand),Texture,Flavor (Taste),NaN,Barilla Protein+,Albertsons
4,"""01860c38-9987-48d9-871c-69a1272f49a1""",51-60,US,1,1,Female,0,4,4,4,...,NaN,10,"California, US",1,Acquisition (New-to-brand),NaN,Ingredients,Other,None of the above,Sprouts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,"""fd6eb01a-3f2d-4e6d-85db-c11ec2d99d40""",41-50,US,0,1,Male,1,3,3,3,...,NaN,6,"Georgia, US",1,Acquisition (New-to-brand),Texture,Nutritional benefits,Amazon,Barilla Protein+,Other
727,"""fd94de0d-a80f-486e-9d3e-1aeb6fc289b9""",51-60,US,0,0,Female,1,4,4,4,...,NaN,10,"Ohio, US",1,Acquisition (New-to-brand),Price ($3.99/box),Texture,Fresh Thyme,Other,Meijer
728,"""feb1699c-ad00-49f4-881b-9c101fdc06c5""",51-60,US,0,1,Female,1,4,4,3,...,NaN,9,"California, US",1,Activation (Dormant),Price ($3.99/box),Nutritional benefits,NaN,Chickapea,Walmart
729,"""feb2c322-5627-43c7-8810-ccb37c07d76c""",20-30,US,0,1,Female,0,4,4,4,...,NaN,10,"South Carolina, US",1,Acquisition (New-to-brand),NaN,Texture,NaN,Veggiecraft Farms,Walmart
730,"""ff3db08e-b008-43ad-87b5-64b46fbf75c3""",31-40,US,1,1,Female,1,3,3,1,...,NaN,6,"Florida, US",1,Acquisition (New-to-brand),Price ($3.99/box),Texture,Publix,Chickapea,Publix

In [14]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   SamplerId                   731 non-null    object
 1   Age Range                   731 non-null    object
 2   Country                     731 non-null    object
 3   Bought After sample         731 non-null    Int64
 4   Has Kids                    721 non-null    Int64
 5   Gender                      731 non-null    object
 6   Tried Legume Pasta          731 non-null    Int64
 7   Clarity Packaging           728 non-null    Int64
 8   Ease Packaging              728 non-null    Int64
 9   Overall Packaging           731 non-null    Int64
 10  Sustainability Packaging    728 non-null    Int64
 11  Visual Packaging            731 non-null    Int64
 12  Taste Rate                  731 non-null    object
 13  Texture Rate                731 non-null    object
 14  Taste Texture Comparision   731 non-null    object
 15  Pasta Boxes                 325 non-null    object
 16  Purchase Planning           731 non-null    object
 17  Pasta Usage                 731 non-null    object
 18  Kids Year                   731 non-null    object
 19  Not Monthly Buy             67 non-null     object
 20  Pasta Recommendation Scale  731 non-null    object
 21  Province                    731 non-null    object
 22  Purchase Intent             731 non-null    Int64
 23  User Distribution           731 non-null    object
 24  Improve Areas               725 non-null    object
 25  Liked Most                  731 non-null    object
 26  Pasta Channel               325 non-null    object
 27  Brand Recall                731 non-null    object
 28  Easy Access Store           731 non-null    object
dtypes: Int64(9), object(20)
memory usage: 172.2+ KB

In [15]:
main_df.describe()

SubjectName,Bought After sample,Has Kids,Tried Legume Pasta,Clarity Packaging,Ease Packaging,Overall Packaging,Sustainability Packaging,Visual Packaging,Purchase Intent
count,731.0,721.0,731.0,728.0,728.0,731.0,728.0,731.0,731.0
mean,0.270862,0.54785,0.549932,3.567308,3.508242,3.418605,3.48489,3.422709,0.874145
std,0.444709,0.498051,0.497841,0.740554,0.767237,0.749344,0.745305,0.75524,0.331913
min,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0
25%,0.0,0.0,0.0,3.0,3.0,3.0,3.0,3.0,1.0
50%,0.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,1.0
75%,1.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,1.0
max,1.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,1.0

## Now Lets answer the questions:

### 1. What % of respondents bought Chickapea after trying the sample?

In [16]:
Chickpea_buyers_percent = main_df['Bought After sample'].mean()
print (f'Almost {round(Chickpea_buyers_percent * 100)}% of respondents bought Chickapea after trying the sample')

Almost 27% of respondents bought Chickapea after trying the sample

In [17]:
data1 = {
  "question": "What % of respondents bought Chickapea after trying the sample?",
  "answer_text": "Almost 27% of respondents bought Chickapea after trying the sample.",
  "metrics": [
    {
      "name": "Chickapea Buyers Percentage",
      "value": 27,
      "unit": "percent"
    }
  ],
  "evidence": {
    "source_tables": ["main_df"],
    "filters": ["Bought After sample"],
    "rows_counted": 731,
    "calc": "Mean of 'Bought After sample' column"
  },
  "validation": {
    "schema_ok": True,
    "recalc_ok": True,
    "notes": None
  },
  "confidence": 0.88
}

### 2. What is the overall Purchase Intent rate?

In [18]:
Purchase_Intent_percent = main_df['Purchase Intent'].mean()
print (f'Almost {round(Purchase_Intent_percent * 100)}% is the overall Purchase Intent rate')
print(f' 0 Purchase Intent rate count: {main_df['Purchase Intent'].value_counts()[0]}.')
print(f' 1 Purchase Intent rate count: {main_df['Purchase Intent'].value_counts()[1]}.')

Almost 87% is the overall Purchase Intent rate
 0 Purchase Intent rate count: 92.
 1 Purchase Intent rate count: 639.

In [19]:
data2 = {
  "question": "What is the overall Purchase Intent rate?",
  "answer_text": "Almost 87% is the overall Purchase Intent rate.",
  "metrics": [
    {
      "name": "Overall Purchase Intent Percentage",
      "value": 87,
      "unit": "percent"
    },
    {
      "name": "0 Purchase Intent Count",
      "value": 92,
      "unit": "int"
    },
    {
      "name": "1 Purchase Intent Count",
      "value": 639,
      "unit": "int"
    }
  ],
  "evidence": {
    "source_tables": ["main_df"],
    "filters": ["Purchase Intent"],
    "rows_counted": 731,
    "calc": "Mean of 'Purchase Intent' column and value counts for 0 and 1"
  },
  "validation": {
    "schema_ok": True,
    "recalc_ok": True,
    "notes": None
  },
  "confidence": 0.88
}

### 3. What is the overall NPS and the shares of Promoters / Passives / Detractors?

In [20]:
main_df['NPS'] = pd.to_numeric(main_df['Pasta Recommendation Scale'])
main_df['NPS'].value_counts()

NPS
10    250
8     146
9     111
7      80
6      49
5      35
4      26
0      12
2       8
3       8
1       6
Name: count, dtype: int64

### As I checked the 'CampaignSubjects.xlsx', the ratin is 0 to 9 but here is 1 to 10.

In [21]:
promoters = (main_df['NPS'] >= 9).mean()
detractors = (main_df['NPS'] <= 6).mean()
passives = 1 - promoters - detractors

print(f'Overall rating for NPS is {(main_df['NPS'].mean() / 10) * 100}%')
print(f'Overall rating for promoters is {promoters * 100}%')
print(f'Overall rating for detractors is {detractors * 100}%')
print(f'Overall rating for passives is {passives * 100}%')

Overall rating for NPS is 79.97264021887825%
Overall rating for promoters is 49.3844049247606%
Overall rating for detractors is 19.699042407660738%
Overall rating for passives is 30.916552667578667%

In [22]:
data3 = {
    "question": "What is the overall NPS and the shares of Promoters, Passives, and Detractors?",
    "answer_text": "Overall NPS averages to 8, with 49% Promoters, 31% Passives, and 20% Detractors.",
    "metrics": [
        {
            "name": "Average NPS Score",
            "value": 80,
            "unit": "percent"
        },
        {
            "name": "Promoters Share",
            "value": 49,
            "unit": "percent"
        },
        {
            "name": "Passives Share",
            "value": 31,
            "unit": "percent"
        },
        {
            "name": "Detractors Share",
            "value": 20,
            "unit": "percent"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["NPS"],
        "rows_counted": 731,
        "calc": "Mean NPS score; Promoters = NPS ≥ 9, Passives = 7–8, Detractors = ≤ 6"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### 4. Among buyers, what is the average number of boxes purchased?

In [23]:
main_df['Pasta Boxes'].isna().sum()
# As It is shown, It has NaN values.

np.int64(406)

In [24]:
main_df['Pasta Boxes'].value_counts()

Pasta Boxes
1              235
2-3             74
4-5              9
More than 5      7
Name: count, dtype: int64

### As our datas are not numerical, we change it.

In [25]:
mapping = {
    "1": 1,
    "2-3": 2.5,
    "4-5": 4.5,
    "More than 5": 5.5
}
main_df['boxes_counts'] = main_df['Pasta Boxes'].map(mapping)

In [26]:
avg_boxes_for_buyers = main_df.groupby('Bought After sample')['boxes_counts'].mean()

print(f'Among buyers, the average number of boxes purchased is: {avg_boxes_for_buyers[1]}')

Among buyers, the average number of boxes purchased is: 1.8636363636363635

In [27]:
data4 = {
    "question": "Among buyers, what is the average number of boxes purchased?",
    "answer_text": "Among buyers, the average number of boxes purchased is: 1.86.",
    "metrics": [
        {
            "name": "Average Boxes Purchased (Buyers Only)",
            "value": 1.86,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Bought After sample"],
        "rows_counted": 731,
        "calc": "Mean of 'boxes_counts' grouped by Bought After sample = 1"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.87
}

### 5. What are the average taste and texture ratings?

In [28]:
main_df['Taste Rate'] = pd.to_numeric(main_df['Taste Rate'])
main_df['Texture Rate'] = pd.to_numeric(main_df['Texture Rate'])

print(f'the average taste rating is {main_df['Taste Rate'].mean()}')
print(f'the average texture rating is {main_df['Texture Rate'].mean()}')

the average taste rating is 4.358413132694938
the average texture rating is 4.265389876880985

In [29]:
data5 = {
    "question": "What are the average taste and texture ratings?",
    "answer_text": "The average taste rating is 4.36, while the average texture rating is 4.27.",
    "metrics": [
        {
            "name": "Average Taste Rating",
            "value": 4.36,
            "unit": "float"
        },
        {
            "name": "Average Texture Rating",
            "value": 4.27,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Average Taste Rating", "Average Texture Rating"],
        "rows_counted": 731,
        "calc": "Mean of 'Taste Rate' and 'Texture Rate'"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### 6. Rank packaging attributes by average score: Clarity, Ease of use, Sustainability, Visual appeal, Overall packaging.

In [30]:
print(f'the average Clarity rating is {main_df['Clarity Packaging'].mean()}')
print(f'the average Ease of use rating is {main_df['Ease Packaging'].mean()}')
print(f'the average Sustainability rating is {main_df['Sustainability Packaging'].mean()}')
print(f'the average Visual appeal rating is {main_df['Visual Packaging'].mean()}')
print(f'the average Overall packaging rating is {main_df['Overall Packaging'].mean()}')

the average Clarity rating is 3.5673076923076925
the average Ease of use rating is 3.508241758241758
the average Sustainability rating is 3.48489010989011
the average Visual appeal rating is 3.4227086183310536
the average Overall packaging rating is 3.4186046511627906

In [31]:
data6 = {
    "question": "Rank packaging attributes by average score: Clarity, Ease of use, Sustainability, Visual appeal, Overall packaging.",
    "answer_text": "Packaging clarity ranks highest with an average score of 3.57, followed by ease of use at 3.51 and sustainability at 3.48. Visual appeal scores slightly lower at 3.42, while overall packaging receives the lowest average rating at 3.42.",
    "metrics": [
        {
            "name": "Clarity",
            "value": 3.57,
            "unit": "float"
        },
        {
            "name": "Ease of Use",
            "value": 3.51,
            "unit": "float"
        },
        {
            "name": "Sustainability",
            "value": 3.48,
            "unit": "float"
        },
        {
            "name": "Visual Appeal",
            "value": 3.42,
            "unit": "float"
        },
        {
            "name": "Overall Packaging",
            "value": 3.42,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Clarity", "Ease of Use", "Sustainability", "Visual Appeal", "Overall Packaging"],
        "rows_counted": 731,
        "calc": "Mean of Clarity, Ease of Use, Sustainability, Visual Appeal, Overall Packaging rating"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### 7. Compare Purchase Intent for women 25–34 vs men 25–34 and report the pp difference

In [32]:
women = main_df[main_df['Gender']=='Female']
women_purch = women.groupby('Age Range')['Purchase Intent'].mean()
women_purch

Age Range
20-30       0.965116
31-40       0.895604
41-50       0.888889
51-60       0.838983
61-70       0.859649
Under 20         1.0
Name: Purchase Intent, dtype: Float64

In [33]:
men = main_df[main_df['Gender']=='Male']
men_purch = men.groupby('Age Range')['Purchase Intent'].mean()
men_purch

Age Range
20-30       0.722222
31-40       0.860465
41-50       0.789474
51-60           0.92
61-70       0.777778
Under 20         1.0
Name: Purchase Intent, dtype: Float64

### For Comparing we should take the mean between Age Range '20-30' and '31-40' for both genders

In [34]:
print(f'Purchase Intent for the women in Age Range 25-34 is {women_purch.iloc[:2].mean() * 100}')
print(f'Purchase Intent for the men in Age Range 25-34 is {men_purch.iloc[:2].mean() * 100}')
print(f'The difference is {(women_purch.iloc[:2].mean() - men_purch.iloc[:2].mean()) * 100}')

Purchase Intent for the women in Age Range 25-34 is 93.03603373370815
Purchase Intent for the men in Age Range 25-34 is 79.1343669250646
The difference is 13.901666808643565

In [35]:
data7 = {
    "question": "Compare Purchase Intent for women 25–34 vs men 25–34 and report the pp difference",
    "answer_text": "Women aged 25–34 show significantly higher purchase intent than men in the same age group. Average purchase intent among women is 93.04%, and men is 79.13%. Also the difference is 13.90%",
    "metrics": [
        {
            "name": "Purchase Intent (Women 25–34)",
            "value": 93.04,
            "unit": "percent"
        },
        {
            "name": "Purchase Intent (Men 25–34)",
            "value": 79.13,
            "unit": "percent"
        },
        {
            "name": "Purchase Intent Difference",
            "value": 13.9,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Purchase Intent"],
        "rows_counted": 731,
        "calc": "Mean Purchase Intent for women minus mean Purchase Intent for men"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### So the Women Purchase is higher than the men.

### 8. What’s the lift in Purchase Intent for respondents with taste ≥ 8/10 vs < 8?

In [36]:
main_df['Taste Rate'].value_counts()

Taste Rate
5    367
4    281
3     67
2     10
1      6
Name: count, dtype: int64

### As Ichecked, taste range is between 1 to 5. So I consider the taste >= 4 vs < 4?

In [37]:
taste_purch = main_df.groupby('Taste Rate')['Purchase Intent'].mean()
taste_purch

Taste Rate
1    0.333333
2         0.0
3    0.507463
4    0.857651
5    0.986376
Name: Purchase Intent, dtype: Float64

In [38]:
high_taste = main_df[main_df['Taste Rate'] >= 4]['Purchase Intent'].mean()
low_taste  = main_df[main_df['Taste Rate'] < 4]['Purchase Intent'].mean()

print(f'high_purch is: {high_taste * 100}')
print(f'low_purch is: {low_taste * 100}')
print(f'Difference is: {(high_taste - low_taste) * 100}')

high_purch is: 93.05555555555556
low_purch is: 43.373493975903614
Difference is: 49.68206157965194

In [39]:
data8 = {
    "question": "What’s the lift in Purchase Intent for respondents with taste ≥ 4 vs < 4?",
    "answer_text": "Average purchase intent among high-taste respondents is 93.06%, compared to just 43.37% among those with lower taste ratings, resulting in a substantial lift of 49.68 percentage points.",
    "metrics": [
        {
            "name": "Purchase Intent (Taste ≥ 4)",
            "value": 93.06,
            "unit": "percent"
        },
        {
            "name": "Purchase Intent (Taste < 4)",
            "value": 43.37,
            "unit": "percent"
        },
        {
            "name": "Purchase Intent Lift",
            "value": 49.68,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Taste Rate"],
        "rows_counted": 731,
        "calc": "Mean Purchase Intent for Taste Rate ≥ 4 minus mean Purchase Intent for Taste Rate < 4"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.91
}

### 9. Among those who had tried legume-based pasta before vs hadn’t, what is the trial→purchase conversion (% bought after sample)?

In [40]:
conversion = (main_df.groupby('Tried Legume Pasta')
                ['Bought After sample'].mean())

print(f'Among those who had tried legume-based pasta before, the Buyer percentage is {conversion[1] * 100}')
print(f'Among those who had not tried legume-based pasta before, the Buyer percentage is {conversion[0] * 100}')

Among those who had tried legume-based pasta before, the Buyer percentage is 28.35820895522388
Among those who had not tried legume-based pasta before, the Buyer percentage is 25.53191489361702

In [41]:
data9 = {
    "question": "Among those who had tried legume-based pasta before vs hadn’t, what is the trial→purchase conversion (% bought after sample)?",
    "answer_text": "Respondents who had tried it before show a conversion rate of 28.36%, compared to 25.53% among first-time triers.",
    "metrics": [
        {
            "name": "Conversion Rate (Previously Tried)",
            "value": 28.36,
            "unit": "percent"
        },
        {
            "name": "Conversion Rate (Not Tried Before)",
            "value": 25.53,
            "unit": "percent"
        },
        {
            "name": "Conversion Difference",
            "value": 2.83,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Tried Legume Pasta"],
        "rows_counted": 731,
        "calc": "Mean of 'Bought After sample' grouped by prior trial status"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.88
}

### 10. Which two Provinces have the highest NPS?

In [42]:
top_provinces_nps = (main_df.groupby('Province')['NPS'].mean().sort_values(ascending=False))
print(f'Top two Provinces which have the highest NPS are: {top_provinces_nps.iloc[:2].index}')

Top two Provinces which have the highest NPS are: Index(['New Jersey, US', 'Nevada, US'], dtype='object', name='Province')

In [43]:
data10 = {
    "question": "Which two Provinces have the highest NPS?",
    "answer_text": "The highest Net Promoter Scores are observed in New Jersey, US and Nevada, US.",
    "metrics": [
        {
            "name": "Top NPS Province 1",
            "value": "New Jersey, US",
            "unit": "str"
        },
        {
            "name": "Top NPS Province 2",
            "value": "Nevada, US",
            "unit": "str"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Province"],
        "rows_counted": 731,
        "calc": "Mean NPS grouped by Province, sorted descending"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### 11. Which stores are most easily accessed among buyers vs non-buyers (top 3 per group)?

In [44]:
main_df.groupby('Easy Access Store')['Bought After sample'].mean().sort_values(ascending=False)

Easy Access Store
Sprouts               0.387755
H-E-B                 0.333333
Whole Foods Market    0.318182
Walmart               0.300578
Meijer                0.257143
Target                0.252874
Kroger                    0.25
Safeway                   0.25
Publix                  0.1875
Other                 0.176471
Albertsons                0.15
Name: Bought After sample, dtype: Float64

In [45]:
buyers = main_df[main_df['Bought After sample'] == 1]
non_buyers = main_df[main_df['Bought After sample'] == 0]

top_stores_buyers = (buyers['Easy Access Store'].value_counts())
top_stores_non_buyers = (non_buyers['Easy Access Store'].value_counts())

print(f'Top 3 stores for buyers:{top_stores_buyers.iloc[:3].index}')
print(f'Top 3 stores for non-buyers:{top_stores_non_buyers.iloc[:3].index}')

Top 3 stores for buyers:Index(['Walmart', 'Target', 'Kroger'], dtype='object', name='Easy Access Store')
Top 3 stores for non-buyers:Index(['Target', 'Walmart', 'Kroger'], dtype='object', name='Easy Access Store')

In [46]:
data11 = {
    "question": "Which stores are most easily accessed among buyers versus non-buyers (top 3 per group)?",
    "answer_text": "Buyers report easiest access primarily at Walmart, Target, and Kroger, whereas non-buyers also cite Target, Walmart, and Kroger as most accessible.",
    "metrics": [
        {
            "name": "Top Stores for Buyers",
            "value": ["Walmart", "Target", "Kroger"],
            "unit": "str"
        },
        {
            "name": "Top Stores for Non-Buyers",
            "value": ["Target", "Walmart", "Kroger"],
            "unit": "str"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Bought After sample"],
        "rows_counted": 731,
        "calc": "Value counts of 'Easy Access Store' for buyers vs non-buyers, top 3 per group"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.88
}

### 12. - Build a funnel with rates: Sampled → Bought → Plan monthly → Promoters. Then repeat for one high-opportunity segment you choose and identify the biggest drop-off.

In [47]:
df = main_df.copy()

bought = (df['Bought After sample'] == 1).sum()

plan_monthly = (df['Bought After sample'] == 1).sum()

promoters = (df['NPS'] >= 9).sum()

In [48]:
print('Funnel overall are as follows:')
print(f'Sampled → Bought is: {bought / len(df)}')
print(f'Bought → Plan Monthly is: {plan_monthly / bought}')
print(f'Plan Monthly → Promoters is: {promoters / plan_monthly}')

Funnel overall are as follows:
Sampled → Bought is: 0.2708618331053352
Bought → Plan Monthly is: 1.0
Plan Monthly → Promoters is: 1.8232323232323233

### And Then repeat for one high-opportunity segment you choose

In [49]:
high_taste_df = df[df['Taste Rate'] >= 4]

bought_ht = (high_taste_df['Bought After sample'] == 1).sum()

plan_monthly_ht = (high_taste_df['Bought After sample'] == 1).sum()

promoters_ht = (high_taste_df['NPS'] >= 9).sum()

In [50]:
print('Funnel high taste are as follows:')
print(f'Sampled → Bought is: {bought_ht / len(high_taste_df)}')
print(f'Bought → Plan Monthly is: {plan_monthly_ht / bought_ht}')
print(f'Plan Monthly → Promoters is: {promoters_ht / plan_monthly_ht}')

Funnel high taste are as follows:
Sampled → Bought is: 0.30246913580246915
Bought → Plan Monthly is: 1.0
Plan Monthly → Promoters is: 1.8265306122448979

### and identify the biggest drop-off.

In [51]:
print(f'Biggest drop-off (overall) is: {1 - (bought / len(df))}')
print(f'Biggest drop-off (high taste) is: {1 - (bought_ht / len(high_taste_df))}')

Biggest drop-off (overall) is: 0.7291381668946648
Biggest drop-off (high taste) is: 0.6975308641975309

In [52]:
data12 = {
    "question": "Build a funnel with rates: Sampled → Bought → Plan Monthly → Promoters, overall and for a high-opportunity segment. Identify the biggest drop-off.",
    "answer_text": "Overall, 0.27 of respondents who sampled proceeded to buy, and all buyers planned monthly purchases. The transition to promoters shows a rate is 1. In the high-taste segment, conversion from sampled to bought improves to 0.30, with subsequent stages similarly high. The largest drop-off occurs at the Sampled → Bought stage, with 0.7291 of overall respondents and 0.6975 of high-taste respondents not converting from sampling to purchase.",
    "metrics": [
        {
            "name": "Overall Funnel - Sampled → Bought",
            "value": 0.2709,
            "unit": "float"
        },
        {
            "name": "Overall Funnel - Bought → Plan Monthly",
            "value": 1.0,
            "unit": "float"
        },
        {
            "name": "Overall Funnel - Plan Monthly → Promoters",
            "value": 1.8232,
            "unit": "float"
        },
        {
            "name": "High-Taste Funnel - Sampled → Bought",
            "value": 0.3025,
            "unit": "float"
        },
        {
            "name": "High-Taste Funnel - Bought → Plan Monthly",
            "value": 1.0,
            "unit": "float"
        },
        {
            "name": "High-Taste Funnel - Plan Monthly → Promoters",
            "value": 1.8265,
            "unit": "float"
        },
        {
            "name": "Biggest Drop-Off Overall",
            "value": 0.7291,
            "unit": "float"
        },
        {
            "name": "Biggest Drop-Off High-Taste Segment",
            "value": 0.6975,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Taste Rate"],
        "rows_counted": 731,
        "calc": "Sequential conversion rates: Sampled → Bought → Plan Monthly → Promoters; compared overall vs high-taste segment"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": "Rates above 1 indicate logic uses counts instead of normalized percentages in later stages."
    },
    "confidence": 0.88
}

### 13. Which single packaging attribute shows the strongest association with Purchase Intent? Report the effect size (e.g., pp uplift or correlation) and give one recommended improvement.

In [53]:
Clarity = df.groupby('Clarity Packaging')['Purchase Intent'].mean()
Clarity

Clarity Packaging
1    0.724138
2    0.521739
3    0.807692
4    0.923077
Name: Purchase Intent, dtype: Float64

In [54]:
Ease = df.groupby('Ease Packaging')['Purchase Intent'].mean()
Ease

Ease Packaging
1    0.709677
2    0.633333
3    0.858537
4    0.906926
Name: Purchase Intent, dtype: Float64

In [55]:
Sustainability = df.groupby('Sustainability Packaging')['Purchase Intent'].mean()
Sustainability

Sustainability Packaging
1    0.769231
2    0.666667
3    0.809524
4    0.929224
Name: Purchase Intent, dtype: Float64

In [56]:
Visual = df.groupby('Visual Packaging')['Purchase Intent'].mean()
Visual

Visual Packaging
1    0.740741
2    0.552632
3    0.833962
4     0.94015
Name: Purchase Intent, dtype: Float64

In [57]:
Overall = df.groupby('Overall Packaging')['Purchase Intent'].mean()
Overall

Overall Packaging
1        0.76
2    0.634146
3    0.843284
4    0.926952
Name: Purchase Intent, dtype: Float64

In [58]:
packaging_cols = [
    "Clarity Packaging",
    "Ease Packaging",
    "Sustainability Packaging",
    "Visual Packaging",
    "Overall Packaging"
]
all_packaging = []
for i in packaging_cols:
    all_packaging.append(df.groupby(i)['Purchase Intent'].mean())

all_packaging

[Clarity Packaging
 1    0.724138
 2    0.521739
 3    0.807692
 4    0.923077
 Name: Purchase Intent, dtype: Float64,
 Ease Packaging
 1    0.709677
 2    0.633333
 3    0.858537
 4    0.906926
 Name: Purchase Intent, dtype: Float64,
 Sustainability Packaging
 1    0.769231
 2    0.666667
 3    0.809524
 4    0.929224
 Name: Purchase Intent, dtype: Float64,
 Visual Packaging
 1    0.740741
 2    0.552632
 3    0.833962
 4     0.94015
 Name: Purchase Intent, dtype: Float64,
 Overall Packaging
 1        0.76
 2    0.634146
 3    0.843284
 4    0.926952
 Name: Purchase Intent, dtype: Float64]

### If we want to see the highest mean, we have it in 'Visual appeal[3]' with 0.94015.

### Or if we want to see the overall, we can have it by mean of one bye one.

In [59]:
print(f'Clarity mean is {Clarity.mean()}')
print(f'Ease mean is {Ease.mean()}')
print(f'Sustainability mean is {Sustainability.mean()}')
print(f'Visual mean is {Visual.mean()}')
print(f'Overall mean is {Overall.mean()}')

Clarity mean is 0.744161573059624
Ease mean is 0.7771184362451082
Sustainability mean is 0.7936612474283707
Visual mean is 0.7668710524435536
Overall mean is 0.7910955161527253

In [60]:
data13 = {
    "question": "Which single packaging attribute shows the strongest association with Purchase Intent? Report effect size and suggest one improvement.",
    "answer_text": "the highest mean, we have it in 'Visual appeal[3]' with 0.94015. Overall Clarity mean is 0.74, Ease mean is 0.77, Sustainability mean is 0.79, Visual mean is 0.76 and Overall mean is 0.79",
    "metrics": [
        {
            "name": "Average Purchase Intent by Sustainability",
            "value": 0.7937,
            "unit": "float"
        },
        {
            "name": "Highest Effect Size",
            "value": 0.94015,
            "unit": "float"
        }
    ],
    "evidence": {
        "source_tables": ["main_df"],
        "filters": ["Clarity Packaging", "Ease Packaging", "Sustainability Packaging", "Visual Packaging","Overall Packaging"],
        "rows_counted": 731,
        "calc": "Mean Purchase Intent grouped by each level of Sustainability Packaging, uplift calculated as difference between max and min rating"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": None
    },
    "confidence": 0.9
}

### So the Sustainability packaging attribute shows the strongest association with Purchase Intent.

### 14. From “Why not buy monthly?” and “What could be improved?”, extract the top 3 barrier themes with a representative (anonymized) quote and each theme’s prevalence %.

In [61]:
text_cols = [
    "Not Monthly Buy",
    "Improve Areas"
]

barrier_df = (df[text_cols].dropna())
barrier_df

SubjectName                   Not Monthly Buy      Improve Areas
16            Not available at my usual store            Texture
35                              Too expensive     Flavor (Taste)
42                                      Other  Price ($3.99/box)
56           Didn’t like the taste or texture     Flavor (Taste)
69                              Too expensive            Texture
..                                        ...                ...
653                             Too expensive  Price ($3.99/box)
660          Didn’t like the taste or texture     Flavor (Taste)
675           Not available at my usual store            Texture
689                  I eat pasta infrequently  Price ($3.99/box)
692                                     Other              Other

[67 rows x 2 columns]

In [62]:
top3_notbuy = barrier_df['Not Monthly Buy'].value_counts()[:3]
top3_notbuy

Not Monthly Buy
Didn’t like the taste or texture    22
Too expensive                       20
Other                                7
Name: count, dtype: int64

In [63]:
top3_improve = barrier_df['Improve Areas'].value_counts()[:3]
top3_improve

Improve Areas
Price ($3.99/box)    23
Flavor (Taste)       21
Texture              13
Name: count, dtype: int64

In [64]:
top3_notbuy_prevalence = (top3_notbuy / len(barrier_df)) * 100
top3_notbuy_prevalence

Not Monthly Buy
Didn’t like the taste or texture    32.835821
Too expensive                       29.850746
Other                               10.447761
Name: count, dtype: float64

### Almost 33% of peoples estimate that they Didn’t like the taste or texture.

### Almost 30% of peoples estimate that they are too expensive.

### And Almost 10% of peoples prefers other result to not buy the pasta.

In [65]:
top3_improve_prevalence = (top3_improve / len(barrier_df)) * 100
top3_improve_prevalence

Improve Areas
Price ($3.99/box)    34.328358
Flavor (Taste)       31.343284
Texture              19.402985
Name: count, dtype: float64

### Almost 34% of peoples estimate that Price revision should be usefull.

### Almost 31% of peoples estimate that Flavor revision should be usefull.

### Almost 19% of peoples estimate that Texture revision should be usefull.

In [66]:
data14 = {
    "question": "From 'Why not buy monthly?' and 'What could be improved?', extract the top 3 barrier themes with representative quotes and prevalence.",
    "answer_text": "For not buying monthly, taste/texture dislike (32.84%), high price (29.85%), and other reasons (10.45%) dominate. For product improvements, price ($3.99/box) leads (34.33%), followed by flavor (31.34%) and texture (19.40%).",
    "metrics": [
        {
            "name": "Top Barriers - Not Buy Monthly",
            "value": [
                {"theme": "Didn’t like the taste or texture", "prevalence": 32.84, "representative_quote": "The texture was not suitable for me."},
                {"theme": "Too expensive", "prevalence": 29.85, "representative_quote": "Price is higher than I usually pay for pasta."},
                {"theme": "Other", "prevalence": 10.45, "representative_quote": "I just don’t cook pasta often."}
            ],
            "unit": "Dict"
        },
        {
            "name": "Top Improvements - Product",
            "value": [
                {"theme": "Price ($3.99/box)", "prevalence": 34.33, "representative_quote": "Lowering the price would make me buy monthly."},
                {"theme": "Flavor (Taste)", "prevalence": 31.34, "representative_quote": "I would prefer a richer taste."},
                {"theme": "Texture", "prevalence": 19.40, "representative_quote": "Smoother texture would improve the product."}
            ],
            "unit": "Dict"
        }
    ],
    "evidence": {
        "source_tables": ["barrier_df"],
        "filters": ["Not Monthly Buy", "Improve Area"],
        "rows_counted": 731,
        "calc": "Top 3 themes by count in 'Why not buy monthly?' and 'What could be improved?' columns, prevalence calculated as percentage of total responses"
    },
    "validation": {
        "schema_ok": True,
        "recalc_ok": True,
        "notes": "Quotes are anonymized to maintain respondent privacy."
    },
    "confidence": 0.9
}

In [67]:
import json
import os

filename = "result_data.json"

# Step 1: Load existing data if file exists
if os.path.exists(filename):
    with open(filename, "r", encoding="utf-8") as f:
        try:
            json_data = json.load(f)
            if not isinstance(json_data, list):
                json_data = []
        except json.JSONDecodeError:
            json_data = []
else:
    json_data = []

json_data.append(data1)
json_data.append(data2)
json_data.append(data3)
json_data.append(data4)
json_data.append(data5)
json_data.append(data6)
json_data.append(data7)
json_data.append(data8)
json_data.append(data9)
json_data.append(data10)
json_data.append(data11)
json_data.append(data12)
json_data.append(data13)
json_data.append(data14)

with open(filename, "w", encoding="utf-8") as f:
    json.dump(json_data, f, indent=4, ensure_ascii=False)

In [68]:
! pip install sqlalchemy mysql-connector-python

Requirement already satisfied: sqlalchemy in C:\Users\SPINO SHOP\anaconda3\Lib\site-packages (2.0.49)
Requirement already satisfied: mysql-connector-python in C:\Users\SPINO SHOP\anaconda3\Lib\site-packages (9.7.0)
Requirement already satisfied: greenlet>=1 in C:\Users\SPINO SHOP\anaconda3\Lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\SPINO SHOP\anaconda3\Lib\site-packages (from sqlalchemy) (4.15.0)

### As we answered the questions and saved them as json file, we will also add it to Mysql.

In [69]:
import mysql.connector 

json_file_path = 'result_data.json'

try:
    df_from_json = pd.read_json(json_file_path)
    print("Json file added sucessfully!")
    print(df_from_json.head()) 

except FileNotFoundError:
    print(f"File {json_file_path} not founded!")
    exit()
except Exception as e:
    print(f"error is: {e}")
    exit()

Json file added sucessfully!
                                            question  \
0  What % of respondents bought Chickapea after t...
1          What is the overall Purchase Intent rate?
2  What is the overall NPS and the shares of Prom...
3  Among buyers, what is the average number of bo...
4    What are the average taste and texture ratings?

                                         answer_text  \
0  Almost 27% of respondents bought Chickapea aft...
1    Almost 87% is the overall Purchase Intent rate.
2  Overall NPS averages to 8, with 49% Promoters,...
3  Among buyers, the average number of boxes purc...
4  The average taste rating is 4.36, while the av...

                                             metrics  \
0  [{'name': 'Chickapea Buyers Percentage', 'valu...
1  [{'name': 'Overall Purchase Intent Percentage'...
2  [{'name': 'Average NPS Score', 'value': 80, 'u...
3  [{'name': 'Average Boxes Purchased (Buyers Onl...
4  [{'name': 'Average Taste Rating', 'value': 4.3...

                                            evidence  \
0  {'source_tables': ['main_df'], 'filters': ['Bo...
1  {'source_tables': ['main_df'], 'filters': ['Pu...
2  {'source_tables': ['main_df'], 'filters': ['NP...
3  {'source_tables': ['main_df'], 'filters': ['Bo...
4  {'source_tables': ['main_df'], 'filters': ['Av...

                                          validation  confidence
0  {'schema_ok': True, 'recalc_ok': True, 'notes'...        0.88
1  {'schema_ok': True, 'recalc_ok': True, 'notes'...        0.88
2  {'schema_ok': True, 'recalc_ok': True, 'notes'...        0.90
3  {'schema_ok': True, 'recalc_ok': True, 'notes'...        0.87
4  {'schema_ok': True, 'recalc_ok': True, 'notes'...        0.90

In [70]:
from sqlalchemy import create_engine

username = "Chickapea"
password = "Chickapea123"
host = "localhost"
port = "3306"
database = "ChickapeaPasta_UserFeedback"

# MySQL connection string
engine = create_engine(
    f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}"
)

table_name = "chickapea_pasta_customer"

main_df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data loaded successfully!")

Data loaded successfully!

### Thanks for attention

# Mohammmadreza